joint_controller:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 1.0, i: 1.0, d: 0.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 1.0, i: 1.0, d: 0.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 1.0, i: 1.0, d: 0.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 1.0, i: 1.0, d: 0.0}